def get_country_name(country_code: str) -> str:
    """
    Get full country name from two-character ISO country code

    Args:
        country_code (str): Two-character ISO country code (e.g., "US", "GB", "FR")

    Returns:
        str: Full country name or "Unknown" for unrecognized codes
    """
    if not country_code or len(country_code) != 2:
        return "Unknown"

    # Convert to uppercase for consistency
    code = country_code.upper()

    country_mappings = {
        # Major countries
        "US": "United States",
        "CA": "Canada",
        "MX": "Mexico",
        "GB": "United Kingdom",
        "FR": "France",
        "DE": "Germany",
        "IT": "Italy",
        "ES": "Spain",
        "RU": "Russia",
        "CN": "China",
        "JP": "Japan",
        "IN": "India",
        "AU": "Australia",
        "BR": "Brazil",
        "AR": "Argentina",
        # Europe
        "AT": "Austria",
        "BE": "Belgium",
        "BG": "Bulgaria",
        "HR": "Croatia",
        "CY": "Cyprus",
        "CZ": "Czech Republic",
        "DK": "Denmark",
        "EE": "Estonia",
        "FI": "Finland",
        "GR": "Greece",
        "HU": "Hungary",
        "IE": "Ireland",
        "LV": "Latvia",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MT": "Malta",
        "NL": "Netherlands",
        "NO": "Norway",
        "PL": "Poland",
        "PT": "Portugal",
        "RO": "Romania",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SE": "Sweden",
        "CH": "Switzerland",
        "IS": "Iceland",
        "TR": "Turkey",
        "UA": "Ukraine",
        "BY": "Belarus",
        "MD": "Moldova",
        "MK": "North Macedonia",
        "AL": "Albania",
        "BA": "Bosnia and Herzegovina",
        "ME": "Montenegro",
        "RS": "Serbia",
        "XK": "Kosovo",
        "AD": "Andorra",
        "MC": "Monaco",
        "SM": "San Marino",
        "VA": "Vatican City",
        "LI": "Liechtenstein",
        # Asia
        "AF": "Afghanistan",
        "AM": "Armenia",
        "AZ": "Azerbaijan",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BT": "Bhutan",
        "BN": "Brunei",
        "KH": "Cambodia",
        "GE": "Georgia",
        "ID": "Indonesia",
        "IR": "Iran",
        "IQ": "Iraq",
        "IL": "Israel",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Laos",
        "LB": "Lebanon",
        "MY": "Malaysia",
        "MV": "Maldives",
        "MN": "Mongolia",
        "MM": "Myanmar",
        "NP": "Nepal",
        "KP": "North Korea",
        "KR": "South Korea",
        "OM": "Oman",
        "PK": "Pakistan",
        "PS": "Palestine",
        "PH": "Philippines",
        "QA": "Qatar",
        "SA": "Saudi Arabia",
        "SG": "Singapore",
        "LK": "Sri Lanka",
        "SY": "Syria",
        "TW": "Taiwan",
        "TJ": "Tajikistan",
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TM": "Turkmenistan",
        "AE": "United Arab Emirates",
        "UZ": "Uzbekistan",
        "VN": "Vietnam",
        "YE": "Yemen",
        # Africa
        "DZ": "Algeria",
        "AO": "Angola",
        "BJ": "Benin",
        "BW": "Botswana",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "CV": "Cape Verde",
        "CM": "Cameroon",
        "CF": "Central African Republic",
        "TD": "Chad",
        "KM": "Comoros",
        "CG": "Congo",
        "CD": "Democratic Republic of the Congo",
        "CI": "Côte d'Ivoire",
        "DJ": "Djibouti",
        "EG": "Egypt",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "SZ": "Eswatini",
        "ET": "Ethiopia",
        "GA": "Gabon",
        "GM": "Gambia",
        "GH": "Ghana",
        "GN": "Guinea",
        "GW": "Guinea-Bissau",
        "KE": "Kenya",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "MG": "Madagascar",
        "MW": "Malawi",
        "ML": "Mali",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "NA": "Namibia",
        "NE": "Niger",
        "NG": "Nigeria",
        "RW": "Rwanda",
        "ST": "São Tomé and Príncipe",
        "SN": "Senegal",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SO": "Somalia",
        "ZA": "South Africa",
        "SS": "South Sudan",
        "SD": "Sudan",
        "TZ": "Tanzania",
        "TG": "Togo",
        "TN": "Tunisia",
        "UG": "Uganda",
        "ZM": "Zambia",
        "ZW": "Zimbabwe",
        # North America
        "AG": "Antigua and Barbuda",
        "BS": "Bahamas",
        "BB": "Barbados",
        "BZ": "Belize",
        "CR": "Costa Rica",
        "CU": "Cuba",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "SV": "El Salvador",
        "GD": "Grenada",
        "GT": "Guatemala",
        "HT": "Haiti",
        "HN": "Honduras",
        "JM": "Jamaica",
        "NI": "Nicaragua",
        "PA": "Panama",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "VC": "Saint Vincent and the Grenadines",
        "TT": "Trinidad and Tobago",
        # South America
        "BO": "Bolivia",
        "CL": "Chile",
        "CO": "Colombia",
        "EC": "Ecuador",
        "FK": "Falkland Islands",
        "GF": "French Guiana",
        "GY": "Guyana",
        "PY": "Paraguay",
        "PE": "Peru",
        "SR": "Suriname",
        "UY": "Uruguay",
        "VE": "Venezuela",
        # Oceania
        "FJ": "Fiji",
        "KI": "Kiribati",
        "MH": "Marshall Islands",
        "FM": "Micronesia",
        "NR": "Nauru",
        "NZ": "New Zealand",
        "PW": "Palau",
        "PG": "Papua New Guinea",
        "WS": "Samoa",
        "SB": "Solomon Islands",
        "TO": "Tonga",
        "TV": "Tuvalu",
        "VU": "Vanuatu",
        # Special codes
        "XX": "Unknown",
    }

    return country_mappings.get(code, "Unknown")
